services:
  orchestrator:
    build:
      target: "dev"
    command: pnpm --filter stream_orchestrator dev
    stdin_open: true
    user: "${UID}:${GID}"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      - PUID=${UID} # これで内部的にユーザーを切り替えてくれる機能があるか確認
      - PGID=${GID}
