name: Create Release

on:
  push:
    tags:
      - 'v*' # 'v1.0.0', 'v1.2.3' などのタグにマッチ
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: tranpile script
        run: pnpm turbo run build --filter=desktop_client

      - name: Build project (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: pnpm desktop build:linux

      - name: Build project (Windows)
        if: matrix.os == 'windows-latest'
        run: pnpm desktop build:win 

      - name: Create tar.gz archive
        shell: bash 
        run: |
          DIST_DIR="apps/desktop_client/dist"
          ARCHIVE_NAME="app-${{ matrix.os }}.tar.gz"

          tar -czvf "$ARCHIVE_NAME" -C "$DIST_DIR" .

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app-*.tar.gz
